[package]
name = "uttt"
version = "0.1.0"
authors = ["David James <davidcjames+xpe@gmail.com>"]
repository = "https://github.com/bluemont/rs-uttt.git"
homepage = "https://github.com/bluemont/rs-uttt.git"

[dependencies]
